Repository AY1920S1-CS2103-T14-2/main, pull requests merged in 2019-10, with the labels that each got.

#58 Update ui link
  src/main/java/seedu/tarence/logic/commands/AddStudentCommand.java
  src/main/java/seedu/tarence/logic/commands/CommandResult.java
  src/main/java/seedu/tarence/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/tarence/logic/commands/EditCommand.java
  src/main/java/seedu/tarence/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/tarence/logic/parser/EditCommandParser.java
  src/main/java/seedu/tarence/model/Application.java
  src/main/java/seedu/tarence/model/Model.java
  src/main/java/seedu/tarence/model/ModelManager.java
  src/main/java/seedu/tarence/model/module/Module.java
  src/main/java/seedu/tarence/model/module/UniqueModuleList.java
  src/main/java/seedu/tarence/model/tutorial/Tutorial.java
  src/main/java/seedu/tarence/model/tutorial/UniqueTutorialList.java
  src/main/java/seedu/tarence/ui/StudentCard.java
  src/main/java/seedu/tarence/ui/TutorialCard.java
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/TutorialListCard.fxml
  src/test/java/seedu/tarence/logic/commands/AddStudentCommandIntegrationTest.java
  src/test/java/seedu/tarence/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/tarence/logic/commands/CommandTestUtil.java
  src/test/java/seedu/tarence/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/tarence/logic/commands/EditCommandTest.java
  src/test/java/seedu/tarence/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/ModelStub.java
  src/test/java/seedu/tarence/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/tarence/logic/parser/ApplicationParserTest.java
  src/test/java/seedu/tarence/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/tarence/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/tarence/model/module/ModuleTest.java
  src/test/java/seedu/tarence/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/tarence/testutil/StudentUtil.java
  src/test/java/seedu/tarence/testutil/TypicalModules.java
  src/test/java/seedu/tarence/testutil/TypicalStudents.java
Labels: enhancement

#65 Attendance display
  src/main/java/seedu/tarence/logic/LogicManager.java
  src/main/java/seedu/tarence/logic/commands/CommandResult.java
  src/main/java/seedu/tarence/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/MarkAttendanceVerifiedCommand.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/tarence/logic/commands/CommandResultTest.java
Labels: priority.High, severity.Medium, type.Story

#66 Display attendance command
  src/main/java/seedu/tarence/logic/commands/DisplayAttendanceCommand.java
  src/main/java/seedu/tarence/logic/parser/ApplicationParser.java
  src/main/java/seedu/tarence/logic/parser/DisplayAttendanceCommandParser.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/java/seedu/tarence/ui/TutorialCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorialListCard.fxml
  src/test/java/seedu/tarence/logic/commands/DisplayAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/parser/ApplicationParserTest.java
  src/test/java/seedu/tarence/logic/parser/DisplayAttendanceCommandParserTest.java
Labels: priority.Medium, severity.Medium, type.enhancement

#69 Minor GUI support
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, severity.Low, type.enhancement

#67 Add suggested corrections, test for attendance marking
  src/main/java/seedu/tarence/logic/commands/Command.java
  src/main/java/seedu/tarence/logic/commands/DisplayAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/SelectSuggestionCommand.java
  src/main/java/seedu/tarence/logic/finder/Finder.java
  src/main/java/seedu/tarence/model/Application.java
  src/main/java/seedu/tarence/model/Model.java
  src/main/java/seedu/tarence/model/ModelManager.java
  src/test/java/seedu/tarence/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/tarence/logic/commands/DisplayAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/ExportAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/ModelStub.java
Labels: priority.Medium, severity.Medium, type.enhancement

#81 Add find command support and displayAttendance shortcut
  src/main/java/seedu/tarence/logic/commands/DisplayAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/FindCommand.java
  src/main/java/seedu/tarence/logic/parser/DisplayAttendanceCommandParser.java
  src/test/java/seedu/tarence/logic/commands/DisplayAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/FindCommandTest.java
  src/test/java/seedu/tarence/logic/parser/DisplayAttendanceCommandParserTest.java
Labels: priority.Medium, severity.Low, type.enhancement

#82 Add autocomplete feature
  src/main/java/seedu/tarence/logic/AutocompleteHandler.java
  src/main/java/seedu/tarence/logic/Logic.java
  src/main/java/seedu/tarence/logic/LogicManager.java
  src/main/java/seedu/tarence/logic/commands/DisplayAttendanceCommand.java
  src/main/java/seedu/tarence/logic/finder/Finder.java
  src/main/java/seedu/tarence/logic/parser/ApplicationParser.java
  src/main/java/seedu/tarence/logic/parser/ArgumentSingleValue.java
  src/main/java/seedu/tarence/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/tarence/logic/parser/PartialInput.java
  src/main/java/seedu/tarence/logic/parser/PartialInputParser.java
  src/main/java/seedu/tarence/model/Application.java
  src/main/java/seedu/tarence/model/Model.java
  src/main/java/seedu/tarence/model/ModelManager.java
  src/main/java/seedu/tarence/ui/CommandBox.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/tarence/logic/commands/AddStudentCommandIntegrationTest.java
  src/test/java/seedu/tarence/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/tarence/logic/commands/ExportAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/tarence/logic/commands/ModelStub.java
  src/test/java/seedu/tarence/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/tarence/logic/parser/PartialInputParserTest.java
Labels: enhancement, priority.High, severity.Medium

#83 Add tab GUI and supporting command
  src/main/java/seedu/tarence/commons/core/Messages.java
  src/main/java/seedu/tarence/logic/LogicManager.java
  src/main/java/seedu/tarence/logic/commands/ChangeTabCommand.java
  src/main/java/seedu/tarence/logic/commands/CommandResult.java
  src/main/java/seedu/tarence/logic/commands/DisplayAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/FindCommand.java
  src/main/java/seedu/tarence/logic/commands/ListCommand.java
  src/main/java/seedu/tarence/logic/commands/TabNames.java
  src/main/java/seedu/tarence/logic/parser/ApplicationParser.java
  src/main/java/seedu/tarence/model/Application.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/java/seedu/tarence/ui/ModuleCard.java
  src/main/java/seedu/tarence/ui/ModuleListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/test/java/seedu/tarence/logic/commands/ChangeTabCommandTest.java
  src/test/java/seedu/tarence/logic/commands/CommandResultTest.java
  src/test/java/seedu/tarence/logic/parser/ApplicationParserTest.java
Labels: priority.Medium, severity.Medium, type.enhancement

#85 Add saving & reading of Attendance objects
  src/main/java/seedu/tarence/commons/util/JsonUtil.java
  src/main/java/seedu/tarence/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/tarence/model/tutorial/Attendance.java
  src/main/java/seedu/tarence/model/tutorial/TutName.java
  src/main/java/seedu/tarence/model/tutorial/Tutorial.java
  src/main/java/seedu/tarence/storage/JsonAdaptedModule.java
  src/test/data/JsonApplicationStorageTest/invalidAndValidStudentApplication.json
  src/test/data/JsonApplicationStorageTest/validApplication.json
  src/test/java/seedu/tarence/commons/util/JsonUtilTest.java
  src/test/java/seedu/tarence/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/tarence/testutil/JsonUtil.java
Labels: enhancement, priority.Medium, severity.Low, type.Story, type.enhancement

#92 Update developer's Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/AddStudentCommandActivityDiagram.pptx
  docs/diagrams/AddStudentCommandSequenceDiagram.pptx
  docs/diagrams/EditCommandSequenceDiagram.pptx
  docs/diagrams/ListCommandActivityDiagram.pptx
  docs/diagrams/ListCommandSequenceDiagram.pptx
  docs/images/AddStudentCommandActivityDiagram.png
  docs/images/AddStudentCommandSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/ListCommandActivityDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  src/main/java/seedu/tarence/logic/commands/ListCommand.java
Labels: priority.Medium, severity.Low, type.Task

#93 Update developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/tarence/storage/JsonAdaptedPerson.java
  src/main/java/seedu/tarence/storage/JsonSerializableApplication.java
  src/test/java/seedu/tarence/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/tarence/storage/JsonApplicationStorageTest.java
  src/test/java/seedu/tarence/storage/StorageManagerTest.java
Labels: documentation, priority.Low, severity.Low

#94 Add documentation for Mark Attendance feature
  docs/DeveloperGuide.adoc
  docs/diagrams/MarkAttendanceActivityDiagram.puml
  docs/images/MarkAttendanceActivityDiagram.png
Labels: documentation

#103 Add Assignment GUI
  src/main/java/seedu/tarence/commons/core/Messages.java
  src/main/java/seedu/tarence/logic/LogicManager.java
  src/main/java/seedu/tarence/logic/commands/CommandResult.java
  src/main/java/seedu/tarence/logic/commands/DisplayAssignmentScoreCommand.java
  src/main/java/seedu/tarence/logic/commands/DisplayFormat.java
  src/main/java/seedu/tarence/logic/commands/assignment/SetAssignmentScoreCommand.java
  src/main/java/seedu/tarence/logic/parser/ApplicationParser.java
  src/main/java/seedu/tarence/logic/parser/CliSyntax.java
  src/main/java/seedu/tarence/logic/parser/DisplayAssignmentScoreCommandParser.java
  src/main/java/seedu/tarence/ui/AssignmentStatisticsPanel.java
  src/main/java/seedu/tarence/ui/AssignmentTablePanel.java
  src/main/java/seedu/tarence/ui/DefaultAssignmentPanel.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/resources/view/AssignmentStatisticsPanel.fxml
  src/main/resources/view/AssignmentTablePanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DefaultAssignmentPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/tarence/logic/commands/CommandResultTest.java
  src/test/java/seedu/tarence/logic/commands/CommandTestUtil.java
  src/test/java/seedu/tarence/logic/commands/DisplayAssignmentScoreCommandTest.java
  src/test/java/seedu/tarence/logic/parser/ApplicationParserTest.java
  src/test/java/seedu/tarence/logic/parser/DisplayAssignmentScoreCommandParserTest.java
Labels: priority.High, severity.Medium, type.enhancement

#108 Update histogram and userguide
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/tarence/ui/AssignmentStatisticsPanel.java
  src/main/java/seedu/tarence/ui/AssignmentTablePanel.java
  src/main/java/seedu/tarence/ui/AttendancePanel.java
  src/main/java/seedu/tarence/ui/DefaultAssignmentPanel.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/resources/view/AssignmentStatisticsPanel.fxml
  src/main/resources/view/AttendancePanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DefaultAssignmentPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, severity.Medium, type.enhancement
