Repository AY1920S1-CS2103-T14-2/main, pull requests merged in 2019-11, with the labels that each got.

#166 setStudent() v5.0, fixed bugs, standardised message usage format
  src/main/java/seedu/tarence/commons/core/Messages.java
  src/main/java/seedu/tarence/logic/commands/AddModuleCommand.java
  src/main/java/seedu/tarence/logic/commands/AddStudentCommand.java
  src/main/java/seedu/tarence/logic/commands/AddTutorialCommand.java
  src/main/java/seedu/tarence/logic/commands/ChangeTabCommand.java
  src/main/java/seedu/tarence/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/tarence/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/tarence/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/tarence/logic/commands/DisplayAssignmentScoreCommand.java
  src/main/java/seedu/tarence/logic/commands/DisplayAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/EditCommand.java
  src/main/java/seedu/tarence/logic/commands/ExportAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/FindCommand.java
  src/main/java/seedu/tarence/logic/commands/ImportCommand.java
  src/main/java/seedu/tarence/logic/commands/ListCommand.java
  src/main/java/seedu/tarence/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/tarence/logic/commands/SetSemStartCommand.java
  src/main/java/seedu/tarence/logic/commands/assignment/AddAssignmentCommand.java
  src/main/java/seedu/tarence/logic/commands/assignment/DeleteAssignmentCommand.java
  src/main/java/seedu/tarence/logic/commands/assignment/SetAssignmentScoreCommand.java
  src/main/java/seedu/tarence/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/tarence/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/tarence/logic/commands/event/EditEventCommand.java
  src/main/java/seedu/tarence/logic/commands/event/ListEventsCommand.java
  src/main/java/seedu/tarence/logic/finder/Finder.java
  src/main/java/seedu/tarence/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/tarence/logic/parser/ParserUtil.java
  src/main/java/seedu/tarence/logic/parser/event/EditEventCommandParser.java
  src/main/java/seedu/tarence/model/Application.java
  src/main/java/seedu/tarence/model/student/Student.java
  src/main/java/seedu/tarence/model/tutorial/Assignment.java
  src/main/java/seedu/tarence/model/tutorial/Event.java
  src/main/java/seedu/tarence/model/tutorial/TutName.java
  src/main/java/seedu/tarence/model/tutorial/Tutorial.java
  src/main/java/seedu/tarence/model/tutorial/exceptions/EventOverlapException.java
  src/main/java/seedu/tarence/ui/HelpWindow.java
  src/test/java/seedu/tarence/logic/commands/EditCommandTest.java
  src/test/java/seedu/tarence/model/tutorial/TutorialTest.java
  src/test/java/seedu/tarence/testutil/TypicalStudents.java
Labels: bug, documentation

#173 Update userguide
  docs/UserGuide.adoc
Labels: documentation, type.Bug

#174 Add storage for Assignments
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/tarence/MainApp.java
  src/main/java/seedu/tarence/commons/util/JsonUtil.java
  src/main/java/seedu/tarence/logic/LogicManager.java
  src/main/java/seedu/tarence/model/tutorial/Tutorial.java
  src/main/java/seedu/tarence/storage/JsonAdaptedModule.java
  src/main/java/seedu/tarence/storage/JsonStateStorage.java
  src/test/java/seedu/tarence/logic/LogicManagerTest.java
  src/test/java/seedu/tarence/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/tarence/storage/StorageManagerTest.java
Labels: enhancement

#177 Project Portfolio Page update
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/team/ellieyee.adoc
Labels: documentation

#180 Fix issue #154 and Storage bug #178
  docs/team/ahmadhatziq.adoc
  src/main/java/seedu/tarence/commons/util/JsonUtil.java
  src/main/java/seedu/tarence/logic/commands/UndoCommand.java
Labels: bug, priority.High, severity.High

#188 Update docs & checking of same date for setSemStart command
  docs/UserGuide.adoc
  docs/team/ahmadhatziq.adoc
  src/main/java/seedu/tarence/commons/core/Messages.java
  src/main/java/seedu/tarence/commons/util/JsonUtil.java
  src/main/java/seedu/tarence/logic/commands/SetSemStartCommand.java
  src/main/java/seedu/tarence/logic/commands/UndoCommand.java
  src/main/java/seedu/tarence/model/module/Module.java
  src/main/java/seedu/tarence/storage/JsonAdaptedModule.java
Labels: documentation

#189 Undo command, storage for events & other bug fixes
  docs/UserGuide.adoc
  src/main/java/seedu/tarence/MainApp.java
  src/main/java/seedu/tarence/commons/util/JsonUtil.java
  src/main/java/seedu/tarence/logic/commands/ClearCommand.java
  src/main/java/seedu/tarence/logic/commands/SetSemStartCommand.java
  src/main/java/seedu/tarence/logic/commands/UndoCommand.java
  src/main/java/seedu/tarence/logic/parser/ApplicationParser.java
  src/main/java/seedu/tarence/logic/parser/ParserUtil.java
  src/main/java/seedu/tarence/model/Application.java
  src/main/java/seedu/tarence/model/Model.java
  src/main/java/seedu/tarence/model/ReadOnlyApplication.java
  src/main/java/seedu/tarence/model/module/Module.java
  src/main/java/seedu/tarence/model/tutorial/Tutorial.java
  src/main/java/seedu/tarence/storage/JsonAdaptedModule.java
  src/main/java/seedu/tarence/storage/JsonStateStorage.java
  src/test/java/seedu/tarence/storage/JsonAdaptedModuleTest.java
Labels: enhancement

#197 Refactor AssignmentTableDisplay and update Userguide
  docs/UserGuide.adoc
  docs/images/AssignmentTable.png
  docs/images/AttendanceDisplay.png
  docs/images/ListAssignment.png
  src/main/java/seedu/tarence/logic/parser/DisplayAssignmentScoreCommandParser.java
  src/main/java/seedu/tarence/ui/AssignmentListPanel.java
  src/main/java/seedu/tarence/ui/AssignmentStatisticsPanel.java
  src/main/java/seedu/tarence/ui/AssignmentTablePanel.java
  src/main/java/seedu/tarence/ui/AttendancePanel.java
  src/main/java/seedu/tarence/ui/DefaultPanel.java
  src/main/java/seedu/tarence/ui/MainWindow.java
  src/main/java/seedu/tarence/ui/ScoreCard.java
  src/main/resources/view/DefaultPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScoreListCard.fxml
  src/test/java/seedu/tarence/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/tarence/logic/parser/DisplayAssignmentScoreCommandParserTest.java
  src/test/java/seedu/tarence/logic/parser/DisplayAttendanceCommandParserTest.java
Labels: priority.Medium, severity.Medium, type.enhancement

#200 Fixed #122: Time slot overflow bug, semStart storage
  src/main/java/seedu/tarence/logic/LogicManager.java
  src/main/java/seedu/tarence/logic/commands/SetSemStartCommand.java
  src/main/java/seedu/tarence/logic/parser/AddTutorialCommandParser.java
  src/main/java/seedu/tarence/model/module/Module.java
  src/main/java/seedu/tarence/model/tutorial/TimeTable.java
  src/main/java/seedu/tarence/model/tutorial/Tutorial.java
  src/main/java/seedu/tarence/storage/JsonStateStorage.java
Labels: bug

#206 Update docs and DG
  docs/DeveloperGuide.adoc
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoSequenceDiagram.png
  docs/team/ahmadhatziq.adoc
Labels: documentation

#208 Update developer guide and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.pptx
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.pptx
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/ellieyee.adoc
  src/main/java/seedu/tarence/logic/parser/ParserUtil.java
Labels: documentation

#209 Update tag for everyone
  docs/DeveloperGuide.adoc
  docs/team/ahmadhatziq.adoc
  docs/team/zihawkeye.adoc
Labels: documentation

#212 Fix documentation typos & add some minor stuff
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/ahmadhatziq.adoc
Labels: documentation

#215 Shorten PPP
  docs/team/ellieyee.adoc
Labels: documentation
